#
# Copyright © 2016-2025 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

service: pachira-alexa-skill

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 10
  environment:
    TB_URL: ${env:THINGSBOARD_URL}
    TB_USER: ${env:THINGSBOARD_USER}
    TB_PASS: ${env:THINGSBOARD_PASS}

functions:
  alexa:
    handler: dist/index.handler
    events:
      - alexaSmartHome: ${env:ALEXA_SKILL_ID}

plugins:
  - serverless-plugin-typescript

custom:
  serverless-plugin-typescript:
    tsConfigFileLocation: './tsconfig.json'
